version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            # install dependencies needed for running tests
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            # trigger production build
            - npm run prodbuild
artifacts:
    files:
        - '**/*'
    base-directory: 'dist/image-gallery-ng*'
    discard-paths: no
