version: 0.2

phases:
    install:
        commands:
            # install dependencies needed for running tests
            - npm install

    build:
        commands:
            # trigger production build
            - ng run prodbuild
